### PR TITLE
DJAN-107 tequila adoption

### PR DESCRIPTION
**Pull request by jbradberry**
Merge together the `cache`, `balancer`, and `web` roles, and move off into its own repo.

### CODE REVIEW

**Comment by dpoirier** [comment]
I'm wondering if we could improve how we control how we come up with SSL certificates. Right now we have two Boolean variables but three ways to do it. It might be easier to follow if we had one variable whose value told us which way to use.  E.g. `cert_source=letsencrypt|selfsign|provided`?  Or something like that.

**Comment by dpoirier** [comment]
Should we provide a variable to control whether we install and configure memcached?

Also, we don't appear to set `app_minions`.

**Comment by jbradberry** [comment]
app_minions: I've waffled over this in the past, but currently I lean away from providing a default for this.  It assumes too much about the groupings that the servers are put into if we set a default for it.

**Comment by dpoirier** [comment]
TASK [tequila-nginx : allow the app minions through the firewall for memcached] 
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{app_minions}}'). This 
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by dpoirier** [comment]
Missing default value for `force_ssl`.

**Comment by jbradberry** [comment]
I believe that all of the review comments have been addressed, so :shipit:

**Pull request merged**
