### PR TITLE
Adjust the Let's Encrypt renewal frequency to happen daily

### PR DESCRIPTION
**Pull request by jbradberry**
and add some notes to the README.rst file.

TEQ-28

### CODE REVIEW

**Review by dpoirier — COMMENTED** [review]
The change to the ansible cron job scheduling looks fine.  And I would expect it would update any existing job with that name, so users shouldn't need to manually remove existing jobs.

Is it likely that any projects are still using the cron job with the older name? If more than one or two, we could just keep the config that cleans that up, but my guess is there are few if any still around.

**Comment by jbradberry** [comment]
@dpoirier the semantics of the cron module's `name:` parameter is similar to that of the `creates:` directive on a task -- if the named thing already exists, the task is short-circuited.  Hence the instructions for clearing out old versions of the cron job.

I figure that writing it up as one-shot instructions will have wider applicability than a task that makes assumptions about what named jobs may have previously been there.

**Comment by dpoirier** [comment]
Maybe they've changed it? I just tried in Ansible 2.4 and when I kept the same name but changed the schedule, ansible updated the existing cron job.

I tested using adhoc commands like this:

``` ansible localhost -m cron -a "name=testjob day=17 hour=2 minute=5 job=false state=present user=dpoirier"```

**Comment by jbradberry** [comment]
Sigh.

    (ansible) jrb@nebula:~$ cat /etc/cron.d/testjob 
    #Ansible: testjob
    5 2 17 * * root false
    (ansible) jrb@nebula:~$ cat /etc/cron.d/testjob 
    #Ansible: testjob
    6 2 17 * * root false

You are completely correct.  Their documentation is wrong.  Unless it's some kind of undocumented difference between playbooks and ad-hoc commands?

**Comment by jbradberry** [comment]
Or, looking at the code in https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/cron.py, this is just the expected behavior.  I've tried a few versions now, back to 1.9.6, and they all do it (though 1.9.6 will make the change but display it like it wasn't changed...)

I guess I'll reword the documentation I added to note that one can remove the cron job with an ad-hoc command, if one is cleaning up after changing from a Let's Encrypt deployment.

**Comment by jbradberry** [comment]
Good catch.

**Review by dpoirier — APPROVED** [review]

**Pull request merged**
